<?php if(isset($_FLASH)): ?>
<div class="candy-flashmsg">
<?php foreach($_FLASH as $msg): ?>
    <div class="<?= $msg['class'] ?>">
        <?php if(is_array($msg['content'])): ?>
        <ul>
            <?php foreach($msg['content'] as $content): ?>
            <li><?= $content ?></li>
            <?php endforeach; ?>
        </ul>
        <?php else: ?>
            <?= $msg['content'] ?>
        <?php endif; ?>
    </div>
<?php endforeach; ?>
</div>
<?php endif; ?>